### ISSUE TITLE
Formato inválido: Data de nascimento 

### ISSUE THREAD

**Issue by LorhanSohaky** [FilaDigital/back-end#9]
Ao registrar um cliente:
```json
{
  "username": "123",
  "password": "123",
  "nome_completo": "Meu nome",
  "celular": "+551199410209",
  "data_nasc": "08/05/1999",
  "sexo": "masculino",
  "email": "email@gmail.com",
  "is_cliente": true
}
```

Está retornando 500 e o erro foi `sqlalchemy.exc.DataError: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'data_nasc' at row 1")`. Fora isso ao tentar cadastrar novamente um mesmo usuário, ele diz que o mesmo já está cadastrado.

# Possível solução
Verificar os tipos que estão sendo enviados e retornar qual campo está errado. Exemplo:
```json
{
  "error": [ {"code":"birthdate", "detail": "Invalid format. Try YYYY-MM-DD"} ]
}
```

**Comment by alcidesmig** [comment]
Solucionado em 9df123fa5ce135ee85581f5ce7c438a793abaf7b e 69f691ebdc7feca70a53bfb5db398dea14827628
